platform :ios, '9.0'
use_frameworks!

versions = Hash[File.read('../versions').split("\n").map{|i|i.split('=')}]

workspace 'Unity Bridge'

target 'UnityTests' do

end

target 'Unity' do
  pod 'VoxImplantSDK', versions['iOSVersion'].tr('"', '')
end

pre_install do |installer|
  file = File.open("Unity/Version.h", "w")
  file.puts "#define UNITY_BRIDGE_VERSION #{versions['unityVersion']}"
  file.close
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
