/*
 *  Copyright (c) 2011-2020, Zingaya, Inc. All rights reserved.
 */

using System;

namespace Voximplant.Unity
{
    /// <summary>
    /// Represents the method that will handle a Voximplant SDK event.
    /// </summary>
    /// <param name="sender">Sender of the event.</param>
    /// <typeparam name="TSender">The type of the event sender.</typeparam>
    public delegate void SdkEventHandler<in TSender>(TSender sender);

    /// <summary>
    /// Represents the method that will handle a Voximplant SDK event with data.
    /// </summary>
    /// <param name="sender">Sender of the event.</param>
    /// <param name="eventArgs">An object that contains the event data.</param>
    /// <typeparam name="TSender">The type of the event sender.</typeparam>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event. Derived from <see cref="EventArgs"/></typeparam>
    public delegate void SdkEventHandler<in TSender, in TEventArgs>(TSender sender, TEventArgs eventArgs)
        where TEventArgs : EventArgs;
}